using System.Collections.Generic;
using System.IO;

namespace DevelopmentDungeon.Functions
{
    public class ForgePaletteTest
    {
        public static List<string> ObjectList = new List<string>
        {
            @"objects\block\cobble\house_smith_roof\house_smith_roof.scenery",
            @"objects\block\cobble\well\well.scenery",
            @"objects\block\dark_wood\dark_wood_archway\dark_wood_archway.scenery",
            @"objects\block\dark_wood\dark_wood_wall\dark_wood_wall.scenery",
            @"objects\block\dark_wood\dark_wood_wall_double\dark_wood_wall_double.scenery",
            @"objects\block\dark_wood\dark_wood_wall_double_pattern\dark_wood_wall_double_pattern.scenery",
            @"objects\block\dark_wood\dark_wood_wall_double_pattern_r\dark_wood_wall_double_pattern_r.scenery",
            @"objects\block\dark_wood\dark_wood_wall_double_r\dark_wood_wall_double_r.scenery",
            @"objects\block\dark_wood\dark_wood_wall_jail_1\dark_wood_wall_jail_1.scenery",
            @"objects\block\dark_wood\dark_wood_wall_jail_2\dark_wood_wall_jail_2.scenery",
            @"objects\block\dark_wood\dark_wood_wall_jail_3\dark_wood_wall_jail_3.scenery",
            @"objects\block\dark_wood\dark_wood_wall_pattern\dark_wood_wall_pattern.scenery",
            @"objects\block\dark_wood\dark_wood_wall_pattern_r\dark_wood_wall_pattern_r.scenery",
            @"objects\block\dark_wood\torch_post\torch_post.scenery",
            @"objects\block\dark_wood\torch_post_double\torch_post_double.scenery",
            @"objects\block\dark_wood\torch_post_double_dud\torch_post_double_dud.scenery",
            @"objects\block\dark_wood\window_overhang\window_overhang.scenery",
            @"objects\block\dirt\block\block.scenery",
            @"objects\block\dirt\chunk_flat\chunk_flat.scenery",
            @"objects\block\dirt\chunk_small\chunk_small.scenery",
            @"objects\block\flower\dandelion\dandelion.scenery",
            @"objects\block\flower\poppy\poppy.scenery",
            @"objects\block\glass\blue\blue.scenery",
            @"objects\block\glass\blue_big\blue_big.scenery",
            @"objects\block\glass\blue_narrow\blue_narrow.scenery",
            @"objects\block\glass\blue_small\blue_small.scenery",
            @"objects\block\glass\double\double.scenery",
            @"objects\block\glass\part70\part70.scenery",
            @"objects\block\glass\part73\part73.scenery",
            @"objects\block\glass\red\red.scenery",
            @"objects\block\glass\red_big\red_big.scenery",
            @"objects\block\glass\red_narrow\red_narrow.scenery",
            @"objects\block\glass\red_small\red_small.scenery",
            @"objects\block\glass\single\single.scenery",
            @"objects\block\glass\triple\triple.scenery",
            @"objects\block\glass\white_big\white_big.scenery",
            @"objects\block\glass\white_huge\white_huge.scenery",
            @"objects\block\glass\white_large\white_large.scenery",
            @"objects\block\glass\white_small\white_small.scenery",
            @"objects\block\glass\window\window.scenery",
            @"objects\block\grass\block\block.scenery",
            @"objects\block\grass\chunk_cube\chunk_cube.scenery",
            @"objects\block\grass\chunk_flat\chunk_flat.scenery",
            @"objects\block\grass\chunk_long\chunk_long.scenery",
            @"objects\block\grass\chunk_long_narrow\chunk_long_narrow.scenery",
            @"objects\block\grass\chunk_single\chunk_single.scenery",
            @"objects\block\grass\chunk_small\chunk_small.scenery",
            @"objects\block\grass\chunk_small_long\chunk_small_long.scenery",
            @"objects\block\grass\chunk_small_wide\chunk_small_wide.scenery",
            @"objects\block\grass\chunk_wide\chunk_wide.scenery",
            @"objects\block\grass\chunk_wide_narrow\chunk_wide_narrow.scenery",
            @"objects\block\log\block\block.scenery",
            @"objects\block\log\column\column.scenery",
            @"objects\block\log\column_big\column_big.scenery",
            @"objects\block\log\column_small\column_small.scenery",
            @"objects\block\log\tree\tree.scenery",
            @"objects\block\patron\sign_func_a\sign_func_a.scenery",
            @"objects\block\patron\sign_func_b\sign_func_b.scenery",
            @"objects\block\patron\sign_func_c\sign_func_c.scenery",
            @"objects\block\safezone\spleef\spleef.crate",
            @"objects\block\shadow\house_big\house_big.scenery",
            @"objects\block\shadow\house_small\house_small.scenery",
            @"objects\block\shadow\lockout\lockout.scenery",
            @"objects\block\shadow\roof\roof.scenery",
            @"objects\block\shadow\roof_facade\roof_facade.scenery",
            @"objects\block\shadow\spleef_platform\spleef_platform.scenery",
            @"objects\block\shadow\spleef_structure\spleef_structure.scenery",
            @"objects\block\shadow\walls\walls.scenery",
            @"objects\block\slime\bounce\bounce.crate",
            @"objects\block\slime\lockout\lockout.crate",
            @"objects\block\slime\spleef_pads\spleef_pads.scenery",
            @"objects\block\stone\part00\part00.scenery",
            @"objects\block\stone\part01\part01.scenery",
            @"objects\block\stone\part02\part02.scenery",
            @"objects\block\stone\part03\part03.scenery",
            @"objects\block\stone\part04\part04.scenery",
            @"objects\block\stone\part05\part05.scenery",
            @"objects\block\stone\part06\part06.scenery",
            @"objects\block\stone\part07\part07.scenery",
            @"objects\block\stone\part08\part08.scenery",
            @"objects\block\stone\part09\part09.scenery",
            @"objects\block\stone\part10\part10.scenery",
            @"objects\block\stone\part11\part11.scenery",
            @"objects\block\stone\part12\part12.scenery",
            @"objects\block\stone\part13\part13.scenery",
            @"objects\block\stone\part14\part14.scenery",
            @"objects\block\stone\part15\part15.scenery",
            @"objects\block\stone\part16\part16.scenery",
            @"objects\block\stone\part17\part17.scenery",
            @"objects\block\stone\part18\part18.scenery",
            @"objects\block\stone\part19\part19.scenery",
            @"objects\block\stone\part20\part20.scenery",
            @"objects\block\stone\part21\part21.scenery",
            @"objects\block\stone\part22\part22.scenery",
            @"objects\block\stone\part23\part23.scenery",
            @"objects\block\stone\part24\part24.scenery",
            @"objects\block\stone\part25\part25.scenery",
            @"objects\block\stone\part26\part26.scenery",
            @"objects\block\stone\part27\part27.scenery",
            @"objects\block\stone\part28\part28.scenery",
            @"objects\block\stone\part29\part29.scenery",
            @"objects\block\stone\part30\part30.scenery",
            @"objects\block\stone\part31\part31.scenery",
            @"objects\block\stone\part32\part32.scenery",
            @"objects\block\stone\part33\part33.scenery",
            @"objects\block\stone\part34\part34.scenery",
            @"objects\block\stone\part35\part35.scenery",
            @"objects\block\stone\part36\part36.scenery",
            @"objects\block\stone\part37\part37.scenery",
            @"objects\block\stone\part38\part38.scenery",
            @"objects\block\stone\part39\part39.scenery",
            @"objects\block\stone\part40\part40.scenery",
            @"objects\block\stone\part41\part41.scenery",
            @"objects\block\stone\part42\part42.scenery",
            @"objects\block\stone\part43\part43.scenery",
            @"objects\block\stone\part44\part44.scenery",
            @"objects\block\stone\part45\part45.scenery",
            @"objects\block\stone\part46\part46.scenery",
            @"objects\block\stone\part47\part47.scenery",
            @"objects\block\stone\part48\part48.scenery",
            @"objects\block\stone\part49\part49.scenery",
            @"objects\block\stone\part50\part50.scenery",
            @"objects\block\stone\part51\part51.scenery",
            @"objects\block\stone\part52\part52.scenery",
            @"objects\block\stone\part53\part53.scenery",
            @"objects\block\stone\part54\part54.scenery",
            @"objects\block\stone\part55\part55.scenery",
            @"objects\block\stone\part56\part56.scenery",
            @"objects\block\stone\part57\part57.scenery",
            @"objects\block\stone\part58\part58.scenery",
            @"objects\block\stone\part59\part59.scenery",
            @"objects\block\stone\part60\part60.scenery",
            @"objects\block\stone\part61\part61.scenery",
            @"objects\block\stone\part62\part62.scenery",
            @"objects\block\stone\part63\part63.scenery",
            @"objects\block\stone\part64\part64.scenery",
            @"objects\block\stone\part65\part65.scenery",
            @"objects\block\stone\part66\part66.scenery",
            @"objects\block\stone\part67\part67.scenery",
            @"objects\block\stone\part68\part68.scenery",
            @"objects\block\stone\part69\part69.scenery",
            @"objects\block\stone\part71\part71.scenery",
            @"objects\block\stone\part72\part72.scenery",
            @"objects\block\tall_grass\block\block.scenery",
            @"objects\block\tall_grass\chunk\chunk.scenery",
            @"objects\block\water\plane\plane.scenery",
            @"objects\block\water\well\well.scenery",
            @"objects\block\wood\block\block.scenery",
            @"objects\block\wood\bookshelves\bookshelves.scenery",
            @"objects\block\wood\crafting_table\crafting_table.scenery",
            @"objects\block\wood\desk\desk.scenery",
            @"objects\block\wood\house_big_balcony\house_big_balcony.scenery",
            @"objects\block\wood\house_big_fence\house_big_fence.scenery",
            @"objects\block\wood\house_big_floor\house_big_floor.scenery",
            @"objects\block\wood\house_big_roof\house_big_roof.scenery",
            @"objects\block\wood\house_big_roof_slice\house_big_roof_slice.scenery",
            @"objects\block\wood\house_big_roof_slice_flip\house_big_roof_slice_flip.scenery",
            @"objects\block\wood\house_big_roof_slice_flop\house_big_roof_slice_flop.scenery",
            @"objects\block\wood\house_big_stairs\house_big_stairs.scenery",
            @"objects\block\wood\house_big_support\house_big_support.scenery",
            @"objects\block\wood\house_big_wall_back\house_big_wall_back.scenery",
            @"objects\block\wood\house_big_wall_front\house_big_wall_front.scenery",
            @"objects\block\wood\house_big_wall_side\house_big_wall_side.scenery",
            @"objects\block\wood\house_small_doorway\house_small_doorway.scenery",
            @"objects\block\wood\house_small_roof\house_small_roof.scenery",
            @"objects\block\wood\house_small_wall\house_small_wall.scenery",
            @"objects\block\wood\house_smith_roof\house_smith_roof.scenery",
            @"objects\block\wood\house_smith_roof_slice\house_smith_roof_slice.scenery",
            @"objects\block\wood\house_smith_wall_front\house_smith_wall_front.scenery",
            @"objects\block\wood\house_smith_wall_side\house_smith_wall_side.scenery",
            @"objects\block\wood\library_seat_one\library_seat_one.scenery",
            @"objects\block\wood\library_seat_two\library_seat_two.scenery",
            @"objects\block\wood\sign\a\a.scenery",
            @"objects\block\wood\sign\b\b.scenery",
            @"objects\block\wood\sign\c\c.scenery",
            @"objects\block\wood\table\table.scenery",
            @"objects\block\wood\torch\torch.scenery",
            @"objects\block\wood\torch_wall\torch_wall.scenery",
            @"objects\block\wood\torch_wall_double\torch_wall_double.scenery",
            @"objects\block\wood\torch_wall_dud\torch_wall_dud.scenery",
            @"objects\block\wood\wall_desks\wall_desks.scenery",
            @"objects\block\wool\bed\bed.scenery",
        };

        public static void Execute()
        {
            var startIndex = 499;

            var output = "";

            for (int i = 0; i < ObjectList.Count; i++)
            {
                output +=
                $"SetField Palette[{startIndex + i}].Name\n" +
                $"SetField Palette[{startIndex + i}].Type Prop\n" +
                $"SetField Palette[{startIndex + i}].CategoryIndex 9\n" +
                $"SetField Palette[{startIndex + i}].DescriptionIndex -1\n" +
                $"SetField Palette[{startIndex + i}].MaxAllowed 0\n" +
                $"SetField Palette[{startIndex + i}].Object {ObjectList[i]}\n" +
                $"AddBlockElements Palette[{startIndex + i}].Setters\n" +
                $"SetField Palette[{startIndex + i}].Setters[0].Target General_Physics\n" +
                $"SetField Palette[{startIndex + i}].Setters[0].Type Integer\n" +
                $"SetField Palette[{startIndex + i}].Setters[0].IntegerValue 1\n" +
                $"SetField Palette[{startIndex + i}].Setters[0].RealValue 0\n" + 
                $"\n";
            }

            File.WriteAllText("commands.txt", output);
        }
    }
}